import { useCallback } from "react";
import {
  useCharacterActions,
  useLorebookActions,
  usePersonaActions,
  usePromptPresetActions,
  useProviderConnectionActions,
} from "../features/catalog";
import { useRoleplayThreadActions, useMessengerThreadActions } from "../features/modes";
import { type NavContextType } from "../features/navigation";
import {
  useAppImportExportActions,
  useAppSettingsActions,
  useCareDrawerActions,
} from "../features/shell";
import { useAppState } from "./use-app-state";
import { useAppStorageSync } from "./use-app-storage-sync";
import { useLoreRuntimeActions } from "./use-lore-runtime-actions";
import { usePromptPresetFileActions } from "./use-prompt-preset-file-actions";
import { useRippleActions } from "./use-ripple-actions";
import { useViewActions } from "./use-view-actions";

export function useAppController(): NavContextType {
  const {
    view,
    setView,
    sideRailView,
    setSideRailView,
    selectedSurface,
    setSelectedSurface,
    characters,
    setCharacters,
    personas,
    setPersonas,
    lorebooks,
    setLorebooks,
    promptPresets,
    setPromptPresets,
    loreRuntimeStates,
    setLoreRuntimeStates,
    macroVariableStates,
    setMacroVariableStates,
    providerConnections,
    setProviderConnections,
    roleplayThreads,
    setRoleplayThreads,
    messengerThreads,
    setMessengerThreads,
    rippleStates,
    setRippleStates,
    messengerStorageMode,
    setMessengerStorageMode,
    messengerStorageStatus,
    setMessengerStorageStatus,
    messengerStorageMessage,
    setMessengerStorageMessage,
    droppedRecordCountByCollection,
    setDroppedRecordCountByCollection,
    storageLoadErrorMessageByCollection,
    setStorageLoadErrorMessageByCollection,
    remoteRuntimeUrl,
    setRemoteRuntimeUrlState,
    appSettings,
    setAppSettings,
    storageReady,
    setStorageReady,
    careOpen,
    setCareOpen,
    careTab,
    setCareTab,
  } = useAppState();

  const {
    setView: setNavView,
    registerViewLeaveGuard,
    requestLeaveCurrentView,
    setSideRailView: setNavSideRailView,
    setSelectedSurface: setNavSelectedSurface,
    openRoleplayThread,
    openMessengerThread,
  } = useViewActions({
    setView,
    setSideRailView,
    setSelectedSurface,
  });
  const prepareForStorageReplacement = useCallback(() => {
    if (!requestLeaveCurrentView()) return false;
    setView({ kind: "pond" });
    return true;
  }, [requestLeaveCurrentView, setView]);

  const {
    checkAppStorageStale,
    commitAppStorageImport,
    flushAppStorageSaves,
    importRecoveryState,
    reloadAppStorage,
    restoreLastPreImportBackup,
    savePromptPresetImport,
    runPromptPresetRelationshipMutation,
    runPromptPresetCatalogMutation,
    storageHasUnsavedChanges,
  } = useAppStorageSync({
    appSettings,
    characters,
    personas,
    lorebooks,
    promptPresets,
    loreRuntimeStates,
    macroVariableStates,
    providerConnections,
    roleplayThreads,
    messengerThreads,
    rippleStates,
    remoteRuntimeUrl,
    setAppSettings,
    setCharacters,
    setPersonas,
    setLorebooks,
    setPromptPresets,
    setLoreRuntimeStates,
    setMacroVariableStates,
    setProviderConnections,
    setRoleplayThreads,
    setMessengerThreads,
    setRippleStates,
    setMessengerStorageMode,
    setMessengerStorageStatus,
    setMessengerStorageMessage,
    prepareForStorageReplacement,
    setDroppedRecordCountByCollection,
    setStorageLoadErrorMessageByCollection,
    setStorageReady,
    storageReady,
  });

  const {
    setRemoteRuntimeUrl,
    setSendOnEnterSurface,
    setConfirmRelease,
    setSurfaceStatus,
    setShoalSortMode,
    setActiveMessengerConnectionId,
    updateAppSettings,
  } = useAppSettingsActions({
    remoteRuntimeUrl,
    setAppSettings,
    setRemoteRuntimeUrlState,
    setStorageReady,
    setMessengerStorageStatus,
    setMessengerStorageMessage,
    prepareForStorageReplacement,
  });

  const { createStorageBundle, importStorageBundle, importLegacyData } = useAppImportExportActions({
    appSettings,
    characters,
    personas,
    lorebooks,
    promptPresets,
    loreRuntimeStates,
    macroVariableStates,
    providerConnections,
    roleplayThreads,
    messengerThreads,
    rippleStates,
    setSelectedSurface,
    setView: setNavView,
    commitAppStorageImport,
  });

  const { setCareOpen: setNavCareOpen, setCareTab: setNavCareTab } = useCareDrawerActions({
    careOpen,
    setCareOpen,
    setCareTab,
  });

  const { createCharacter, updateCharacter, duplicateCharacter, deleteCharacter } =
    useCharacterActions({
      characters,
      setCharacters,
      setRoleplayThreads,
      setMessengerThreads,
    });

  const { createPersona, updatePersona, duplicatePersona, deletePersona } = usePersonaActions({
    personas,
    setPersonas,
    setRoleplayThreads,
    setMessengerThreads,
  });

  const {
    createLorebookEntry,
    updateLorebookEntry,
    duplicateLorebookEntry,
    deleteLorebookEntry,
    createLorebook,
    updateLorebook,
    deleteLorebook,
  } = useLorebookActions({
    lorebooks,
    setLorebooks,
    setAppSettings,
    setCharacters,
    setPersonas,
    setRoleplayThreads,
    setMessengerThreads,
  });

  const {
    createPromptPreset,
    updatePromptPreset,
    duplicatePromptPreset,
    prepareImportedPromptPreset,
    addImportedPromptPreset,
    deletePromptPreset,
  } = usePromptPresetActions({
    promptPresets,
    runPromptPresetRelationshipMutation,
    runPromptPresetCatalogMutation,
    setPromptPresets,
  });
  const {
    promptPresetFileHost,
    promptPresetFileStatus,
    setPromptPresetFileStatus,
    importPromptPresetFile,
    openPromptPresetFile,
    exportPromptPresetFile,
  } = usePromptPresetFileActions({
    promptPresets,
    prepareImportedPromptPreset,
    addImportedPromptPreset,
    savePromptPresetImport,
    flushAppStorageSaves,
  });

  const {
    createProviderConnection,
    updateProviderConnection,
    duplicateProviderConnection,
    deleteProviderConnection,
  } = useProviderConnectionActions({
    providerConnections,
    setProviderConnections,
    setAppSettings,
    setRoleplayThreads,
    setMessengerThreads,
  });

  const {
    createRoleplayThread,
    updateRoleplayThread,
    updateRoleplayThreadById,
    appendRoleplayThreadEntries,
    renameRoleplayThread,
    clearRoleplayThreadEntries,
    deleteRoleplayThread,
    roleplayPromptPresetRepairNotices,
    clearRoleplayPromptPresetRepairNotice,
  } = useRoleplayThreadActions({
    activeMessengerConnectionId: appSettings.activeMessengerConnectionId,
    defaultPromptPresetId: appSettings.defaultPromptPresetId,
    promptPresets,
    characters,
    roleplayThreads,
    personas,
    providerConnections,
    setRoleplayThreads,
    setLoreRuntimeStates,
    setMacroVariableStates,
    setRippleStates,
    setView: setNavView,
    view,
    openChatSettings: () => setNavSideRailView("chat-settings"),
    openRoleplayThread,
  });

  const {
    createMessengerThread,
    updateMessengerThread,
    updateMessengerThreadById,
    appendMessengerThreadMessages,
    renameMessengerThread,
    clearMessengerThreadMessages,
    deleteMessengerThread,
    messengerPromptPresetRepairNotices,
    clearMessengerPromptPresetRepairNotice,
  } = useMessengerThreadActions({
    activeMessengerConnectionId: appSettings.activeMessengerConnectionId,
    defaultPromptPresetId: appSettings.defaultPromptPresetId,
    promptPresets,
    characters,
    messengerThreads,
    personas,
    providerConnections,
    setMessengerThreads,
    setLoreRuntimeStates,
    setMacroVariableStates,
    setView: setNavView,
    view,
    openChatSettings: () => setNavSideRailView("chat-settings"),
    openMessengerThread,
  });

  const { getRippleState, createRipple, updateRipple, deleteRipple } = useRippleActions({
    rippleStates,
    setRippleStates,
  });

  const { getLoreRuntimeState, updateLoreRuntimeState } = useLoreRuntimeActions({
    loreRuntimeStates,
    setLoreRuntimeStates,
  });

  return {
    view,
    sideRailView,
    selectedSurface,
    characters,
    personas,
    lorebooks,
    promptPresets,
    promptPresetFileHost,
    promptPresetFileStatus,
    loreRuntimeStates,
    macroVariableStates,
    providerConnections,
    roleplayThreads,
    messengerThreads,
    messengerStorageMode,
    messengerStorageStatus,
    messengerStorageMessage,
    droppedRecordCountByCollection,
    storageLoadErrorMessageByCollection,
    storageReady,
    storageHasUnsavedChanges,
    importRecoveryState,
    rippleStates,
    remoteRuntimeUrl,
    appSettings,
    careOpen,
    careTab,
    setView: setNavView,
    registerViewLeaveGuard,
    requestLeaveCurrentView,
    setSideRailView: setNavSideRailView,
    setSelectedSurface: setNavSelectedSurface,
    createCharacter,
    updateCharacter,
    duplicateCharacter,
    deleteCharacter,
    createPersona,
    updatePersona,
    duplicatePersona,
    deletePersona,
    createLorebookEntry,
    updateLorebookEntry,
    duplicateLorebookEntry,
    deleteLorebookEntry,
    createLorebook,
    updateLorebook,
    deleteLorebook,
    createPromptPreset,
    updatePromptPreset,
    duplicatePromptPreset,
    deletePromptPreset,
    importPromptPresetFile,
    openPromptPresetFile,
    exportPromptPresetFile,
    setPromptPresetFileStatus,
    createProviderConnection,
    updateProviderConnection,
    duplicateProviderConnection,
    deleteProviderConnection,
    createRoleplayThread,
    updateRoleplayThread,
    updateRoleplayThreadById,
    appendRoleplayThreadEntries,
    renameRoleplayThread,
    clearRoleplayThreadEntries,
    deleteRoleplayThread,
    roleplayPromptPresetRepairNotices,
    clearRoleplayPromptPresetRepairNotice,
    openRoleplayThread,
    createMessengerThread,
    updateMessengerThread,
    updateMessengerThreadById,
    appendMessengerThreadMessages,
    renameMessengerThread,
    clearMessengerThreadMessages,
    deleteMessengerThread,
    messengerPromptPresetRepairNotices,
    clearMessengerPromptPresetRepairNotice,
    openMessengerThread,
    getRippleState,
    createRipple,
    updateRipple,
    deleteRipple,
    getLoreRuntimeState,
    updateLoreRuntimeState,
    updateMacroVariableStates: setMacroVariableStates,
    createStorageBundle,
    checkAppStorageStale,
    flushAppStorageSaves,
    importStorageBundle,
    importLegacyData,
    reloadAppStorage,
    restoreLastPreImportBackup,
    setRemoteRuntimeUrl,
    updateAppSettings,
    setSendOnEnterSurface,
    setConfirmRelease,
    setSurfaceStatus,
    setShoalSortMode,
    setActiveMessengerConnectionId,
    setCareOpen: setNavCareOpen,
    setCareTab: setNavCareTab,
  };
}
